#!/bin/bash
echo "Ramesh:: Hello Suresh, Good Morning"
echo "Suresh:: Hello Ramesh, Good Morning"
echo "Ramesh:: How are you?"
echo "Suresh:: I am fine, What about you?"
echo "Ramesh:: I am also fine"
echo "Ramesh:: What are you doing these days?"  
echo "Suresh:: I am learning Shell Scripting"
echo "Ramesh:: Oh! That's great"
echo "Suresh:: Yes, It is very interesting" 
echo "Ramesh:: Good Bye"
echo "Suresh:: Good Bye"
echo "Ramesh:: Take Care"
echo "Suresh:: You too"
echo "Ramesh:: See you later"
echo "Suresh:: Sure"
echo "Ramesh:: Bye"
echo "Suresh:: Bye"
echo "Ramesh:: Have a nice day"
echo "Suresh:: You too, Have a nice day"